libros/urls.py
from django.urls import path
from . import views

urlpatterns=[
	path('',views.index,name='index'),
	path('books/', views.BookListView.as_view(), name='books'),
	path('galeria', views.galeria, name='galeria'),
    path('formulario', views.formulario, name='formulario'),
	path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('libros/', include('libros.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    

]

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EMAIL_BACKEND	=	'django.core.mail.backends.console.EmailBackend'

libros/models.py
from django.db import models
from django.urls import reverse 
import uuid 

class Genero(models.Model):

    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Book(models.Model):
    
	titulo = models.CharField(max_length=200)
	autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
	descripcion = models.TextField(max_length=1000, help_text='Pequeña descripcion del libro')
	genero = models.ManyToManyField(Genero)
    
	def __str__(self):
		return self.titulo
    
	def get_absolute_url(self):
		"""Returns the url to access a detail record for this book."""
		return reverse('galeria', args=[str(self.id)])





class Estado_libro(models.Model):

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Identificación única para este libro en particular en toda la biblioteca')
 
	book = models.ForeignKey('book', on_delete=models.SET_NULL, null=True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)

	LOAN_STATUS = (
		('d', 'Disponible'),
		('a', 'Agotado'),
		
	)

	status = models.CharField(
		max_length=1,
		choices=LOAN_STATUS,
		blank=True,
		default='d',
		help_text='Estado de libro',
	)

	class Meta:
		ordering = ['due_back']

	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.id} ({self.book.titulo})'


class Autor(models.Model):
	"""Model representing an author."""
	primer_nombre = models.CharField(max_length=100)
	apellido = models.CharField(max_length=100)
	año_nacimiento = models.DateField(null=True, blank=True)
	año_defuncion = models.DateField('defuncion', null=True, blank=True)

	class Meta:
		ordering = ['apellido', 'primer_nombre']

	def get_absolute_url(self):
		return reverse('autor-detail', args=[str(self.id)])

	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.apellido}, {self.primer_nombre}'


class Clientes(models.Model):
	"""Model representing an Clientes."""
	primer_nombre = models.CharField(max_length=100)
	apellido = models.CharField(max_length=100)
	año_nacimiento = models.DateField(null=True, blank=True)
	direccion = models.CharField(max_length=100)

	class Meta:
		ordering = ['apellido', 'primer_nombre']

	

	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.apellido}, {self.primer_nombre}'

libros/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.

from django import forms


class RenewBookForm(forms.Form):
    """Form for a librarian to renew books."""
    renewal_date = forms.DateField(
            help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
            
        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

libros/views.py
from django.shortcuts import render
from .models import Book, Autor, Estado_libro, Genero
from django.views import generic
def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    # Genera contadores de algunos de los objetos principales
    num_libros=Book.objects.all().count()
    num_instancias=Estado_libro.objects.all().count()
    # Libros disponibles (status = 'd')
    num_libros_d=Estado_libro.objects.filter(status__exact='d').count()
    num_autors=Autor.objects.count()  # El 'all()' esta implícito por defecto.
    
    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(
        request,
        'index.html',
        context={'num_libros':num_libros,'num_instancias':num_instancias,'num_libros_d':num_libros_d,'num_autors':num_autors},
    )
    
def galeria(request):
    return render(request,'galeria.html')  

def formulario(request):
    return render(request,'formulario.html') 
    
class BookListView(generic.ListView):
    model = Book
    paginate_by = 10
class BookDetailView(generic.DetailView):
    model = Book



from django.views import generic

class AutorDetailView(generic.DetailView):
    """Generic class-based detail view for an autor."""
    model = Autor


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Autor

class AutorCreate(CreateView):
    model = Autor
    fields = '__all__'
    initial={'fecha_de_muerte':'05/01/2018',}

libros/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

libros/templates/formulario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creación de cuentas</title>
    <link rel="shortcut icon" type="image/x-icon" href=" {% static 'img/iconolibros.png'  %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/estilosF.css' %}">
    <script src="{% static 'js/form.js' %}"></script>
</head>

<body onload="cargarProvincias()">
    
<div class="contenedor">
            <header>
               <div class="contenedor">
        <h1 class="icon-libros">Mis Libros</h1>
        <input type="checkbox" id="menu-bar">
        <label class="fontawesome-align-justify" for="menu-bar"></label>
                  <nav class="menu">
                    <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                    <a class="nav-link" href="{% url 'galeria' %}">Galeria</a>
                    <a href="http://MatiNico.pythonanywhere.com/admin/login/?next=/admin/">admin</a>
                    <a class="nav-link" href="{% url 'formulario' %}">contacto</a>
                  </nav>
                </div>
            </header>
</div>

       
<main>
    <section id="banner">
        <div class="slider">
 <ul>
<li>
        <img src="{% static 'img/sliderlibros.jpg' %}" alt="">
        <img src="{% static 'img/slider2.jpg' %}" alt="">

</li>
</ul>
</div>

        <div class="contenedor">
            <h2>Libera tu imaginación</h2>
            <p>La lectura abre mundos infinitos</p>
        </div>
    </section>
    
</main>
        

<div class="container">
    <div class="col-xl-12"  style="background-color:#942C14">
      <div class="info">
            <p class="numero"></p>
            <p class="numero"></p>
                <div id="redes">
                    <div class="redes"> 
                    <a href="http://www.facebook.com" ><img src="{% static 'img/face.tiff' %}" width="50" height="50" alt=""> </a>
                    <a href="http://www.instagram.com" > <img src="{% static 'img/ig.tiff '%}'" width="50" height="50" alt=""> </a>
                    <a href="https://plus.google.com" ><img src="{% static 'img/plus.tiff' %}" width="50" height="50" alt=""> </a>
                    <a href="http://www.twitter.com" >  <img src="{% static 'img/tiw.tiff' %}" width="50" height="50" alt=""> </a>
                    </div>
                </div>
        </div>
    </div>
</div>
<div class="fuera">
  <div class="hola" >
        <div class="form__top">
            <h2>Creación de usuario</h2>
        </div>      
        <form name="formulario1" class="form__reg" >
           
                {% csrf_token %}
                <table>
                  <tr><th><label for="id_primer_nombre">Primer nombre:</label></th><td><input type="text" name="primer_nombre" maxlength="100" required id="id_primer_nombre"></td></tr>
                  <tr><th><label for="id_apellido">Apellido:</label></th><td><input type="text" name="apellido" maxlength="100" required id="id_apellido"></td></tr>
                  <tr><th><label for="id_año_nacimiento">Año nacimiento:</label></th><td><input type="text" name="año_nacimiento" id="id_año_nacimiento"></td></tr>
                </table>
                <input type="submit" value="Registrar" />
                
            </form>
        </form>
    </div>
</div>

<footer class="row">
            <div class="col-xs-12">
                <div class="footer">
                    <h3>  Todos los derechos reservados<br>
                        Contacto: +56912353438<br>
                        Email: Libros@gmail.com<br>
                    </h3>
                </div>
            </div>
</footer> 

</body>
</html>

libros/templates/galeria.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Mis Libros</title>
	<link rel="shortcut icon" type="image/x-icon" href=" {% static 'img/iconolibros.png'  %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <header>
        <div class="contenedor">
            <h1 class="icon-dog">Mis Libros</h1>
            <input type="checkbox" id="menu-bar">
            <label class="fontawesome-align-justify" for="menu-bar"></label>
                    <nav class="menu">
                        <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                        <a class="nav-link" href="{% url 'galeria' %}">Info libros</a>
                        <a href="http://MatiNico.pythonanywhere.com/admin/login/?next=/admin/">admin</a>
                        <a class="nav-link" href="{% url 'formulario' %}">contacto</a>
                    </nav>
                </div>
    </header>


<main>
    <section id="banner">
        <div class="slider">
             <ul>
                <li>
                 <img src="{% static 'img/sliderlibros.jpg'%}" alt="">
                 <img src="{% static 'img/slider2.jpg'%}" alt="">
                    
              </li>
             </ul>
</div>

        <div class="contenedor">
            <h2>Libera tu imaginacón</h2>
            <p>La lectura abre mundos infinitos</p>
        </div>
    </section>
    
</main>


<div class="container">
<div class="col-xl-12"  style="background-color:#942C14">
<div class="info">
    <p class="numero"></p>
    <p class="numero"></p>
        <div id="redes">
            <div class="redes"> 
                <a href="http://www.facebook.com" ><img src="{% static 'img/face.tiff' %}" width="50" height="50" alt=""> </a>
                <a href="http://www.instagram.com" > <img src="{% static 'img/ig.tiff '%}'" width="50" height="50" alt=""> </a>
                <a href="https://plus.google.com" ><img src="{% static 'img/plus.tiff' %}" width="50" height="50" alt=""> </a>
                <a href="http://www.twitter.com" >  <img src="{% static 'img/tiw.tiff' %}" width="50" height="50" alt=""> </a>
            </div>
        </div>
</div>
</div>
</div>

 
<br>
<br>


 <!-- galeria -->
 <div class="container-galeria">
    
     
     <!-- imagenes -->
     <div class="img-galeria">

        <!-- Book list --> 
        <h1>Lista de libros: </h1> <br>
        

    {% if galeria %}
    <ul>

      {% for book in galeria %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.titulo}}</a> ({{book.autor}}) 

      </li>
      {% endfor %}

    </ul>

    {% else %}
      <br> <br><p class="je">No existen libros registrados</p>
    {% endif %}       
 <!--Termina el book list-->



     </div>

 </div>
 
 <div class="container-galeria">


<!-- detalles-->

<figure> <h1></h1> <img src="{% static 'img/galeria/portada1.jpg'%}" width="170" height="325" alt=""> </figure>
<br>
<h2>Titulo: {{ book.titulo }}</h2>
<br>
<br> 
  <p class="ja"><strong>Autor:</strong> <a href="">{{ book.autor }}</a></p> <!-- author detail link not yet defined --> <br>

  <p class="ja"><strong>descripcion:</strong> {{ book.descripcion }}</p><br>
  <p class="ja"><strong>Language:</strong> {{ book.language }}</p>  <br>
  <p class="ja"><strong>Genero:</strong> {% for genero in book.genero.all %} {{ genero }}{% if not forloop.last %}, {% endif %}{% endfor %}</p> <br> 

  <div style="margin-left:20px;margin-top:20px">
    

    {% for copy in book.Estado_libro.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>

  <!-- fin detalles-->

 </div>

<footer class="row">
    <div class="col-xs-12">
        <div class="footer">
            <h3>  Todos los derechos reservados<br>
                Contacto: +56912353438<br>
                Email: Libros@gmail.com<br>
            </h3>
        </div>
    </div>
 </footer>  
</body>
</html>

libros/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

libros/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Mis Libros</title>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/iconolibros.png' %}">
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
</head>
<body>
    <header>
        <div class="contenedor">
            <h1 class="icon-libros">Mis Libros</h1>
            <input type="checkbox" id="menu-bar">
            <label class="fontawesome-align-justify" for="menu-bar"></label>
                    <nav class="menu">
                        <a class="nav-link" href="{% url 'index' %}">Inicio</a>
                        <a class="nav-link" href="{% url 'galeria' %}">Galeria</a>
                        <a href="http://MatiNico.pythonanywhere.com/admin/login/?next=/admin/">admin</a>
                        <a class="nav-link" href="{% url 'formulario' %}">contacto</a>
                    </nav>
                </div>
    </header>
    <main>
        <section id="banner">
            <div class="slider">
     <ul>
    <li>
            <img src="{% static 'img/sliderlibros.jpg' %}" alt="">
            <img src="{% static 'img/slider2.jpg' %}" alt="">

    </li>
   </ul>
    </div>

            <div class="contenedor">
                <h2>Libera tu imaginación</h2>
                <p>La lectura abre mundos infinitos</p>
            </div>
        </section>
        
    </main>
    



    <div class="container">
    <div class="col-xl-12"  style="background-color:#942C14">
    <div class="info">
        <p class="numero"></p>
        <p class="numero"></p>
            <div id="redes">
                <div class="redes"> 
                    <a href="http://www.facebook.com" ><img src="{% static 'img/face.tiff' %}" width="50" height="50" alt=""> </a>
                    <a href="http://www.instagram.com" > <img src="{% static 'img/ig.tiff' %}" width="50" height="50" alt=""> </a>
                    <a href="https://plus.google.com" ><img src="{% static 'img/plus.tiff' %}" width="50" height="50" alt=""> </a>
                    <a href="http://www.twitter.com" >  <img src="{% static 'img/tiw.tiff' %}" width="50" height="50" alt="">> </a>
                </div>
            </div>
    </div>
    </div>
    </div>

    <section id="main">
        <h3>Libroos</h3>
        <article class="col">
            <h4>LECTURA</h4>
            <p id="etapa"> IMPORTANCIA </p> 
        <div class="imgsep"><img src="{% static 'img/sep.png' %}" width="80" height="10" alt=""></div>
            <p id="contenido">Mientras más leemos, </p>
            <p id="contenido2">más aprendemos del mundo y sus maravillas. </p>
            <p id="contenidos">Así mismo aumenta tus capacidades </p>
            <p id="contenidos2">cognitivas y linguisticas.</p>
        <div class="imgres"> <img src="{% static 'img/libre.jpg' %}" width="300" height="150" alt=""> </div>
    </article>

    <aside class="col">
        <div class="imgcam"> <img src="{% static 'img/crow.jpg' %}"  width="280" height="180" alt=""> </div>
            <p id="titulo2"> NUEVOS MUNDOS </p>
            <p id="etapa2"> LIBERA TU IMAGINACIÓN </p> 
        <div class="imgsep"><img src="{% static 'img/sep.png' %}" width="80" height="10" alt=""></div>
            <p id="contenido3">Gracias a los libros somos capaces  </p>
            <p id="contenido4">de transportarnos en nuestra mente. </p>
            <p id="contenidos3">Podemos acompañar a nuestros personajes </p>
            <p id="contenidos4"> favoritos en su arduo camino.</p>
    </aside>


    {% block content %}
  <h1>Title: {{ book.titulo }}</h1>

  <p><strong>Autor:</strong> <a href="">{{ book.autor }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>descripcion:</strong> {{ book.descripcion }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genero:</strong> {% for genero in book.genero.all %} {{ genero }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.Estado_libro.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}
    </section>

    <footer class="row">
        <div class="col-xs-12">       
                  <div class="footer">
              
                    <h3>  Todos los derechos reservados<br>
                        Contacto: +56912353438<br>
                        Email: Libros@gmail.com<br>
                    </h3>
                </div>
        </div>
    </footer>   

</body>
</html>

libros/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}